### ISSUE TITLE
Crash on loading.

### ISSUE THREAD

**Issue by katubug** [iLexiconn/LLibrary#137]
Here's the crash my players and I keep getting: https://paste.dimdev.org/evehefufoq.mccrash

It happens mostly on startup or server connect. We're using llibrary-1.7.18-1.12.2, iceandfire-1.7.1-1.12.2, fossilsarcheology-8.0.0, and Forge 14.23.5.2825. Please let me know if you need any other information from me!

**Comment by ghost** [comment]
same problem

**Comment by Gegy** [comment]
Hmm, odd. Does this occur when just using LLibrary/Ice and Fire or LLibrary/Fossils and Archaeology individually?

**Comment by ghost** [comment]
ice and fire

**Comment by katubug** [comment]
I'm not sure, I'll have to test. I'm not sure when I can get to it, but I'll do my best!

**Comment by dstavis** [comment]
I had a similar issue prompted by trying to install ice and fire. It also happens without Ice and Fire or any other mods, and just LLibrary. I just opened and promptly closed a new issue about mine.

https://github.com/iLexiconn/LLibrary/issues/143

Mine got fixed when I updated LLibrary from 1.14 to 1.19.

**Comment by Nathanngamer181** [comment]
i keep getting a crash  weaponlib (mw-1.11.6_mc1.11.2.jar)
  Chiseled Me ASM (chiseled-me-1.1.2.jar)
  llibrary (LLibrary-1.11.2.jar)
  PLCore (JurassiCraft-1.11.2.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 7/25/19 6:02 PM
Description: Initializing game

java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    net/minecraft/client/renderer/EntityRenderer.func_78467_g(F)V @245: aload_2
  Reason:
    Type float (current frame, locals[2]) is not assignable to reference type
  Current Frame:
    bci: @245
    flags: { }
    locals: { 'net/minecraft/client/renderer/EntityRenderer', float, float, 'net/minecraft/entity/Entity', float, double, double_2nd, double, double_2nd, double, double_2nd }
    stack: { float }
  Bytecode:
    0x0000000: 2ab4 00be b601 534e 2db6 0316 2db8 02ee
    0x0000010: 6e2d 23b8 01f7 5945 6a38 042d b403 192d
    0x0000020: b403 1c2d b403 1967 238d 6b63 3905 2db4
    0x0000030: 031f 2db4 0322 2db4 031f 6723 8d6b 6317
    0x0000040: 048d 6339 072d b403 252d b403 282d b403
    0x0000050: 2567 238d 6b63 3909 2dc1 0278 9900 882d
    0x0000060: c002 78b6 032b 9900 7e17 048d 0f63 9038
    0x0000070: 040b 1303 2c0b b803 0e2a b400 beb4 0170
    0x0000080: b403 2f9a 022a bb00 1c59 2db7 019a 3a0b
    0x0000090: 2ab4 00be b401 9819 0bb6 0333 3a0c 2ab4
    0x00000a0: 00be b401 9819 0b19 0c2d b803 372d b403
    0x00000b0: 3a2d b403 3d2d b403 3a66 236a 6213 033e
    0x00000c0: 620b 1303 3f0b b802 d72d b403 422d b403
    0x00000d0: 452d b403 4266 236a 6213 033f 0b0b b802
    0x00000e0: d7a7 01cc 2ab4 00be b401 70b4 0348 9e01
    0x00000f0: b52a b400 9e2c 23b8 034d 2ab4 009e 6623
    0x0000100: 6a62 8d24 8d6b 390d 2ab4 00be b401 70b4
    0x0000110: 032f 9900 0f0b 0b18 0d77 90b8 030e a701
    0x0000120: 822d b403 3d38 0f2d b403 4538 102a b400
    0x0000130: beb4 0170 b403 4805 a000 0b17 1013 033e
    0x0000140: 6238 1017 0f13 034e 6ab8 02de 7617 1013
    0x0000150: 034e 6ab8 0305 6a8d 180d 6b39 1117 0f13
    0x0000160: 034e 6ab8 0305 1710 1303 4e6a b803 056a
    0x0000170: 8d18 0d6b 3913 1710 1303 4e6a b802 de76
    0x0000180: 8d18 0d6b 3915 0336 1715 1710 08a2 00bf
    0x0000190: 1517 047e 0568 0464 8638 1815 1704 7a04
    0x00001a0: 7e05 6804 6486 3819 1517 057a 047e 0568
    0x00001b0: 0464 8638 1a17 1813 01a5 246a 6a38 1817
    0x00001c0: 1913 01a5 246a 6a38 1917 1a13 01a5 246a
    0x00001d0: 6a38 1a2a b400 beb4 0198 bb02 0c59 1805
    0x00001e0: 1718 8d63 1807 1719 8d63 1809 171a 8d63
    0x00001f0: b703 51bb 020c 5918 0518 1167 1718 8d63
    0x0000200: 171a 8d63 1807 1815 6717 198d 6318 0918
    0x0000210: 1367 171a 8d63 b703 51b6 0354 3a1b 191b
    0x0000220: c600 2619 1bb4 0212 bb02 0c59 1805 1807
    0x0000230: 1809 b703 51b6 0216 391c 181c 180d 989c
    0x0000240: 0007 181c 390d 8417 01a7 ff40 2ab4 00be
    0x0000250: b401 70b4 0348 05a0 000c 1303 3e0b 0c0b
    0x0000260: b802 d72d b403 4517 1066 0c0b 0bb8 02d7
    0x0000270: 2db4 033d 170f 660b 0c0b b802 d70b 0b18
    0x0000280: 0d77 90b8 030e 170f 2db4 033d 660b 0c0b
    0x0000290: b802 d717 102d b403 4566 0c0b 0bb8 02d7
    0x00002a0: a700 0d0b 0b13 017e 246a b803 0e2a b400
    0x00002b0: beb4 0170 b403 2f9a 00a1 2db4 033a 2db4
    0x00002c0: 033d 2db4 033a 6623 6a62 1303 3e62 380b
    0x00002d0: 2db4 0342 2db4 0345 2db4 0342 6623 6a62
    0x00002e0: 380c 0b38 0f2d c103 5699 0022 2dc0 0356
    0x00002f0: 3a10 1910 b403 5919 10b4 035c 1910 b403
    0x0000300: 5966 236a 6213 033e 6238 0b2a b400 beb4
    0x0000310: 0198 2d23 b802 b23a 10bb 0015 592a 2d19
    0x0000320: 1023 8d17 0b17 0c17 0fb7 035f 3a1e b203
    0x0000330: 6519 1eb6 036b 5719 1eb6 036e 0b0b 0cb8
    0x0000340: 02d7 191e b603 710c 0b0b b802 d719 1eb6
    0x0000350: 0374 0b0c 0bb8 02d7 0b17 0476 0bb8 030e
    0x0000360: 2db4 0319 2db4 031c 2db4 0319 6723 8d6b
    0x0000370: 6339 052d b403 1f2d b403 222d b403 1f67
    0x0000380: 238d 6b63 1704 8d63 3907 2db4 0325 2db4
    0x0000390: 0328 2db4 0325 6723 8d6b 6339 092a 2ab4
    0x00003a0: 00be b401 d018 0518 0718 0923 b603 78b5
    0x00003b0: 037a b1                                
  Stackmap Table:
    full_frame(@228,{Object[#2],Float,Float,Object[#505],Float,Double,Double,Double},{})
    append_frame(@289,Top,Top,Double)
    append_frame(@323,Float,Float)
    full_frame(@393,{Object[#2],Float,Float,Object[#505],Float,Double,Double,Double,Top,Top,Double,Float,Float,Double,Double,Double,Integer},{})
    full_frame(@582,{Object[#2],Float,Float,Object[#505],Float,Double,Double,Double,Top,Top,Double,Float,Float,Double,Double,Double,Integer,Float,Float,Float,Object[#36]},{})
    full_frame(@588,{Object[#2],Float,Float,Object[#505],Float,Double,Double,Double,Top,Top,Double,Float,Float,Double,Double,Double,Integer},{})
    same_frame(@611)
    full_frame(@672,{Object[#2],Float,Float,Object[#505],Float,Double,Double,Double,Top,Top,Double},{})
    chop_frame(@675,3)
    same_frame(@685)
    full_frame(@779,{Object[#2],Float,Float,Object[#505],Float,Double,Double,Double,Float,Float,Top,Top,Float},{})
    full_frame(@856,{Object[#2],Float,Float,Object[#505],Float,Double,Double,Double},{})

	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:510)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:510)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 408288632 bytes (389 MB) / 1073741824 bytes (1024 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.1.2588 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2588.jar) 
	UCH	forge{13.20.1.2588} [Minecraft Forge] (forge-1.11.2-13.20.1.2588.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCH	chiseled_me{1.1.2} [Chiseled Me] (chiseled-me-1.1.2.jar) 
	UCH	chiselsandbits{13.16} [Chisels & Bits] (chiselsandbits-13.16.jar) 
	UCH	ageofabyssalcraft{0.6} [Abyssalcraft Addon] (Engender+mod+1.11.2+0.6 (1).jar) 
	UCH	ageofchaos{0.6} [Draconic Evolution Addon] (Engender+mod+1.11.2+0.6 (1).jar) 
	UCH	ageofminecraft{0.5} [The Engender Mod] (Engender+mod+1.11.2+0.6 (1).jar) 
	UCH	llibrary{1.7.11} [LLibrary] (LLibrary-1.11.2.jar) 
	UCH	jurassicraft{2.1.9} [JurassiCraft] (JurassiCraft-1.11.2.jar) 
	UCH	mekanism{9.3.5} [Mekanism] (Mekanism-Mod-Core-1.11.2.jar) 
	UCH	mekanismgenerators{9.3.5} [MekanismGenerators] (Mekanism-Mod-Generators-1.11.2.jar) 
	UCH	mekanismtools{9.3.5} [MekanismTools] (Mekanism-Mod-Tools-1.11.2.jar) 
	UCH	mw{1.11.6} [Modern Warfare] (mw-1.11.6_mc1.11.2.jar) 
	UCH	personalcars{1.2.2} [Personal Cars] (Personal-Cars-1.11.2.jar) 
	Loaded coremods (and transformers): 
weaponlib (mw-1.11.6_mc1.11.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
Chiseled Me ASM (chiseled-me-1.1.2.jar)
  dev.necauqua.mods.cm.asm.Plugin
llibrary (LLibrary-1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
PLCore (JurassiCraft-1.11.2.jar)
  org.jurassicraft.server.pl.PLTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics 4000'
	Launched Version: 1.11.2-forge1.11.2-13.20.1.2588
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4358, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz

**Comment by Nathanngamer181** [comment]
see

**Comment by Nathanngamer181** [comment]
it works from mc mod net but it is to old
