### ISSUE TITLE
Potion Effect Crash

### ISSUE THREAD

**Issue by Tylis20** [iLexiconn/LLibrary#141]
When i drink a potion or eat a rotten potato or flesh, the game crashes. I removed all the mods but LLibrary. It still crashes. Here is my crash log.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.4-1.12.2.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 5/28/19 9:56 PM
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.client.entity.EntityPlayerSP cannot be cast to net.minecraft.entity.player.EntityPlayerMP
	at DamageIndicatorsMod.core.DIEventBus.livingEvent(DIEventBus.java:229)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_104_DIEventBus_livingEvent_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:580)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:181)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at DamageIndicatorsMod.core.DIEventBus.livingEvent(DIEventBus.java:229)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_104_DIEventBus_livingEvent_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:580)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:181)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 1623
	Entity Name: Mitharien
	Entity's Exact location: 237.95, 71.00, 264.75
	Entity's Block location: World: (237,71,264), Chunk: (at 13,4,8 in 14,16; contains blocks 224,0,256 to 239,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.11, -0.08, 0.07
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Mitharien'/1623, l='MpServer', x=237.95, y=71.00, z=264.75]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (232,64,256), Chunk: (at 8,4,0 in 14,16; contains blocks 224,0,256 to 239,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1056 game time, 1056 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 70 total; [EntityZombieVillager['Zombi Köylü'/2048, l='MpServer', x=201.50, y=37.00, z=332.50], EntityZombie['Zombi'/2056, l='MpServer', x=214.50, y=43.00, z=273.50], EntityZombie['Zombi'/2062, l='MpServer', x=215.50, y=43.00, z=272.50], MoCEntitySnake['Snake'/16, l='MpServer', x=202.03, y=83.00, z=272.00], MoCEntitySnake['Snake'/17, l='MpServer', x=204.90, y=81.00, z=270.19], EntityCreeper['Creeper'/2067, l='MpServer', x=195.50, y=50.00, z=247.50], EntitySkeleton['İskelet'/2068, l='MpServer', x=196.52, y=50.00, z=249.72], EntitySkeleton['İskelet'/2069, l='MpServer', x=213.50, y=43.00, z=275.50], MoCEntityBoar['Boar'/26, l='MpServer', x=246.50, y=89.00, z=186.50], MoCEntityBoar['Boar'/27, l='MpServer', x=243.73, y=89.00, z=187.04], EntityZombie['Zombi'/2075, l='MpServer', x=204.50, y=22.00, z=311.50], MoCEntityBoar['Boar'/28, l='MpServer', x=241.65, y=73.00, z=294.56], MoCEntityBoar['Boar'/29, l='MpServer', x=249.24, y=75.00, z=290.30], MoCEntityBoar['Boar'/33, l='MpServer', x=248.50, y=87.00, z=321.50], MoCEntityBoar['Boar'/34, l='MpServer', x=251.50, y=87.00, z=320.50], EntityZombie['Zombi'/2086, l='MpServer', x=210.50, y=61.00, z=224.50], MoCEntityBoar['Boar'/40, l='MpServer', x=292.50, y=72.00, z=299.50], EntityCreeper['Creeper'/2088, l='MpServer', x=158.50, y=16.00, z=249.50], MoCEntityBoar['Boar'/41, l='MpServer', x=299.44, y=77.00, z=298.50], EntitySkeleton['İskelet'/2091, l='MpServer', x=212.50, y=58.00, z=237.50], EntityWitch['Cadı'/2095, l='MpServer', x=204.50, y=61.00, z=222.50], EntityZombie['Zombi'/2096, l='MpServer', x=212.50, y=61.00, z=221.50], EntitySkeleton['İskelet'/2097, l='MpServer', x=229.50, y=13.00, z=208.50], EntityItem['item.tile.mushroom'/2102, l='MpServer', x=207.77, y=46.00, z=256.17], EntityZombie['Zombi'/2104, l='MpServer', x=227.50, y=13.00, z=210.50], EntityItem['item.tile.mushroom'/2107, l='MpServer', x=211.33, y=45.00, z=248.58], EntityItem['item.tile.mushroom'/2110, l='MpServer', x=212.88, y=45.00, z=248.20], EntityCreeper['Creeper'/1639, l='MpServer', x=174.55, y=15.00, z=223.01], EntityCreeper['Creeper'/1640, l='MpServer', x=170.82, y=14.00, z=223.49], MoCEntitySnail['Snail'/1642, l='MpServer', x=193.50, y=78.00, z=310.50], MoCEntitySnail['Snail'/1643, l='MpServer', x=194.50, y=78.00, z=310.50], EntitySkeleton['İskelet'/1656, l='MpServer', x=222.50, y=45.00, z=281.50], MoCEntityAnt['Ant'/1660, l='MpServer', x=195.50, y=84.00, z=288.50], MoCEntityAnt['Ant'/1661, l='MpServer', x=196.50, y=84.00, z=285.50], MoCEntityAnt['Ant'/1662, l='MpServer', x=194.50, y=84.00, z=281.50], EntitySophisticatedWolf['Sophisticated Wolf'/1664, l='MpServer', x=195.50, y=73.00, z=232.50], EntitySophisticatedWolf['Sophisticated Wolf'/1665, l='MpServer', x=199.50, y=73.00, z=232.50], MoCEntityAnt['Ant'/1666, l='MpServer', x=196.50, y=73.00, z=201.50], MoCEntitySnail['Snail'/1667, l='MpServer', x=190.50, y=73.00, z=209.50], MoCEntitySnail['Snail'/1668, l='MpServer', x=190.50, y=73.00, z=208.50], MoCEntitySnail['Snail'/1669, l='MpServer', x=192.50, y=73.00, z=207.50], MoCEntityFly['Fly'/1670, l='MpServer', x=223.50, y=64.00, z=343.50], MoCEntityMaggot['Maggot'/1671, l='MpServer', x=162.50, y=80.00, z=273.50], MoCEntityGoldFish['GoldFish'/1673, l='MpServer', x=187.50, y=70.00, z=203.50], MoCEntityAngler['Angler'/1674, l='MpServer', x=194.50, y=71.00, z=197.50], EntitySpider['Örümcek'/1675, l='MpServer', x=235.72, y=11.00, z=212.31], MoCEntityManticore['Manticore'/1683, l='MpServer', x=256.71, y=22.70, z=204.27], EntityEnderman['Enderman'/1686, l='MpServer', x=203.50, y=63.00, z=228.50], MoCEntityManticore['Manticore'/1696, l='MpServer', x=239.30, y=26.83, z=210.30], MoCEntityRat['Rat'/1697, l='MpServer', x=207.50, y=41.00, z=277.50], EntityZombie['Zombi'/1699, l='MpServer', x=185.50, y=14.00, z=206.50], EntityZombie['Zombi'/1702, l='MpServer', x=184.50, y=14.00, z=206.50], EntityCreeper['Creeper'/1708, l='MpServer', x=170.61, y=53.00, z=246.14], EntitySkeleton['İskelet'/1712, l='MpServer', x=215.50, y=37.00, z=335.50], EntityZombie['Zombi'/1713, l='MpServer', x=173.50, y=53.00, z=239.50], EntityCreeper['Creeper'/1718, l='MpServer', x=171.50, y=15.00, z=316.50], MoCEntityWerewolf['Werewolf'/1722, l='MpServer', x=207.50, y=13.00, z=193.50], EntityCreeper['Creeper'/1723, l='MpServer', x=171.50, y=15.00, z=315.50], EntityWitch['Cadı'/1724, l='MpServer', x=164.50, y=19.00, z=225.50], EntitySkeleton['İskelet'/1725, l='MpServer', x=209.50, y=46.00, z=258.50], EntityItem['item.item.mocegg.26'/1727, l='MpServer', x=213.74, y=82.00, z=294.94], EntityPlayerSP['Mitharien'/1623, l='MpServer', x=237.95, y=71.00, z=264.75], EntitySophisticatedWolf['Sophisticated Wolf'/2021, l='MpServer', x=167.50, y=79.00, z=270.50], EntitySophisticatedWolf['Sophisticated Wolf'/2022, l='MpServer', x=194.50, y=73.00, z=226.50], EntityCreeper['Creeper'/2025, l='MpServer', x=169.50, y=14.00, z=223.50], MoCEntityWerewolf['Werewolf'/2030, l='MpServer', x=205.50, y=13.00, z=193.70], EntitySkeleton['İskelet'/2037, l='MpServer', x=190.50, y=18.00, z=192.50], EntitySkeleton['İskelet'/2038, l='MpServer', x=192.50, y=17.00, z=198.50], MoCEntityWerewolf['Werewolf'/2039, l='MpServer', x=238.50, y=12.00, z=210.50], EntityWitch['Cadı'/2044, l='MpServer', x=208.50, y=61.00, z=222.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 387391048 bytes (369 MB) / 826044416 bytes (787 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version        | Source                               | Signature                                |
	|:------ |:------------------- |:-------------- |:------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2         | minecraft.jar                        | None                                     |
	| LCHIJA | mcp                 | 9.42           | minecraft.jar                        | None                                     |
	| LCHIJA | FML                 | 8.0.99.99      | forge-1.12.2-14.23.5.2838.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2838   | forge-1.12.2-14.23.5.2838.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | damageindicatorsmod | 1.0            | Damage-Indicators-Mod-1.12.2.jar     | None                                     |
	| LCHIJA | infinitylib         | 1.12.2-1.12.0  | InfinityLib-1.12.2.jar               | None                                     |
	| LCHIJA | jei                 | 4.15.0.279     | jei_1.12.2-4.15.0.279.jar            | None                                     |
	| LCHIJA | journeymap          | 1.12.2-5.5.5b7 | JourneyMap-Mod-1.12.2-Unlimited.jar  | None                                     |
	| LCHIJA | radixcore           | 1.12.x-2.2.1   | RadixCore-1.12.2.jar                 | None                                     |
	| LCHIJA | mca                 | 1.12.2-5.3.1   | Minecraft-Comes-Alive-Mod-1.12.2.jar | None                                     |
	| LCHIJA | mocreatures         | 12.0.5         | Mo-Creatures-Mod-1.12.2.jar          | None                                     |
	| LCHIJA | sophisticatedwolves | 3.13.8         | Sophisticated-Wolves-Mod-1.12.2.jar  | None                                     |
	| LCHIJA | spartanshields      | 1.5.1          | Spartan-Shields-Mod-1.12.2.jar       | None                                     |
	| LCHIJA | treechopper         | 1.2.4          | Tree-Chopper-Mod-1.12.2.jar          | None                                     |
	| LCHIJA | llibrary            | 1.7.10         | llibrary-1.7.10-1.12.2.jar           | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.4-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 430.64' Renderer: 'GeForce 940M/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2838
	LWJGL: 2.9.4
	OpenGL: GeForce 940M/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.64, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Lithos-Core v1.15 for 1.12x.zip
	Current Language: Türkçe (Türkiye)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 430.64
	OpenGlRenderer: GeForce 940M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Gegy** [comment]
Are you sure you removed all mods but LLibrary? At least, this crash log specifically, is caused by Damage Indicators (if indirectly?)

**Comment by Tylis20** [comment]
When I delete the LLibrary, the problem was solved. Bu after you say that, I redownload LLibrary and deleted all the other mods in order to show you. I created a new world and took a rotten flesh from creativity mod and ate it. And yes, it didn't crash. In order to try whether those mods are playable together, I added the damage indicators and relaunched game. The game is crashed, so the two mods are not playable together. Thanks for the information.
