### ISSUE TITLE
llibrary 1.7.19 Unable to configure ModInfo java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by gelonsoft** [iLexiconn/LLibrary#154]
llibrary 1.7.19
==============
```
-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1462620064 bytes (1394 MB) / 5053087744 bytes (4819 MB) up to 6442450944 bytes (6144 MB)
  JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6912m -Xms256m -XX:PermSize=256m -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=c:\dev\
  IntCache: cache: 28, tcache: 94, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2838 207 mods loaded, 207 mods active 
```
==============
Error in logfile:
===========
```
[16:38:39] [Client thread/ERROR]: Unable to configure ModInfo
java.lang.IncompatibleClassChangeError: Class net.minecraft.client.resources.Locale does not implement the requested interface java.util.Map
	at net.ilexiconn.llibrary.client.lang.LanguageHandler.addRemoteLocalizations(LanguageHandler.java:91) ~[LanguageHandler.class:?]
	at net.ilexiconn.llibrary.LLibrary$CoreAPIHandler.addRemoteLocalizations(LLibrary.java:111) ~[LLibrary$CoreAPIHandler.class:?]
	at net.ilexiconn.llibrary.server.core.patcher.LLibraryHooks.addRemoteLocalizations(LLibraryHooks.java:31) ~[LLibraryHooks.class:?]
	at net.minecraft.client.resources.Locale.loadLocaleDataFiles(Locale.java:32) ~[cfb.class:?]
	at modinfo.ModInfo.getLocale(ModInfo.java:271) ~[ModInfo.class:1.12.2-5.5.5]
	at modinfo.ModInfo.<init>(ModInfo.java:53) [ModInfo.class:1.12.2-5.5.5]
	at journeymap.client.JourneymapClient.startMapping(JourneymapClient.java:521) [JourneymapClient.class:1.12.2-5.5.5]
	at journeymap.client.task.main.MappingMonitorTask.perform(MappingMonitorTask.java:72) [MappingMonitorTask.class:1.12.2-5.5.5]
	at journeymap.client.task.main.MainTaskController.performTasks(MainTaskController.java:84) [MainTaskController.class:1.12.2-5.5.5]
	at journeymap.client.JourneymapClient.performMainThreadTasks(JourneymapClient.java:654) [JourneymapClient.class:1.12.2-5.5.5]
	at journeymap.client.forge.event.StateTickHandler.onClientTick(StateTickHandler.java:91) [StateTickHandler.class:1.12.2-5.5.5]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2555_StateTickHandler_onClientTick_ClientTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1708) [bib.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```
=============

**Comment by corgiblu** [comment]
also having this error.

**Comment by bre2el** [comment]
An instance of Locale class is incorrectly passed as an argument of type Map of addRemoteLocalizations().
It is a guess from the source code of 1.12.1, I guess "GETFIELD properties" instruction is missing before "INVOKE* addRemoteLocalizations" instruction in LLibraryRuntimePatcher.class of 1.12.2 when transforming Locale.class.

**Comment by rboccunigodfrey** [comment]
Any solutions for this error? I am getting it as well.

**Comment by moddingforreal** [comment]
I am having this issue too, any fix planned or possible so far?
