### ISSUE TITLE
I have a problem when is loading the mods

### ISSUE THREAD

**Issue by skrillexjorge9** [iLexiconn/LLibrary#185]
[21:04:55] [pool-3-thread-1/ERROR] [LLibrary]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.2.7.4.jar)
  iceandfire (iceandfire-1.8.4.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.7.3-SNAPSHOT-20210322.052210-core.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  Wizardry Plugin (wizardry-0.10.8.jar)
  RandomPatches (randompatches-1.12.2-1.22.1.7.jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.21.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 7/11/21 9:04 PM
Description: Failed to receive data from URL: https://gist.githubusercontent.com/gegy1000/7a6d39cf7a2c1f794ffb9037e8146adc/raw/llibrary_patrons.json

java.io.FileNotFoundException: https://gist.githubusercontent.com/gegy1000/7a6d39cf7a2c1f794ffb9037e8146adc/raw/llibrary_patrons.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(AccessController.java:713)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at java.net.URL.openStream(URL.java:1038)
	at net.ilexiconn.llibrary.server.util.WebUtils.readURL(WebUtils.java:60)
	at net.ilexiconn.llibrary.server.util.WebUtils.lambda$readURLAsync$0(WebUtils.java:105)
	at net.ilexiconn.llibrary.server.util.WebUtils$$Lambda$1284/39359495.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

**Comment by quietust** [comment]
Download LLibrary 1.7.20 from https://www.curseforge.com/minecraft/mc-mods/llibrary/files/3116493 and replace the old version in your pack.
