### ISSUE TITLE
First time with this error please help

### ISSUE THREAD

**Issue by IronRighteous** [iLexiconn/LLibrary#201]
when i try to load into my world it crashes on the laoding screen then im met with this error message

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 2/8/23 7:47 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.world.World.getSkyColorBody(World.java:1484)
	at net.minecraft.world.WorldProvider.getSkyColor(WorldProvider.java:463)
	at net.minecraft.world.World.func_72833_a(World.java:1475)
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:2285)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1638)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.world.World.getSkyColorBody(World.java:1484)
	at net.minecraft.world.WorldProvider.getSkyColor(WorldProvider.java:463)
	at net.minecraft.world.World.func_72833_a(World.java:1475)
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:2285)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1638)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)

-- Affected level --
Details:
	Level name: MpServer
	All players: 0 total; []
	Chunk stats: MultiplayerChunkCache: 374, 374
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 13078458 game time, 9225790 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 544856640 bytes (519 MB) / 1912602624 bytes (1824 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.5.2779 Optifine OptiFine_1.12.2_HD_U_E2 22 mods loaded, 22 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID              | Version        | Source                                        | Signature                                |
	|:--------- |:--------------- |:-------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft       | 1.12.2         | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp             | 9.42           | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML             | 8.0.99.99      | forge-1.12.2-14.23.5.2779.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge           | 14.23.5.2779   | forge-1.12.2-14.23.5.2779.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | baubles         | 1.5.2          | Baubles-1.12-1.5.2.jar                        | None                                     |
	| UCHIJAAAA | atum            | 2.0.17         | Atum-1.12.2-2.0.17.jar                        | None                                     |
	| UCHIJAAAA | bibliocraft     | 2.4.5          | BiblioCraft[v2.4.5][MC1.12.2].jar             | None                                     |
	| UCHIJAAAA | biomesoplenty   | 7.0.1.2444     | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar | None                                     |
	| UCHIJAAAA | bookworm        | 1.12.2-2.5.2.1 | bookworm-1.12.2-2.5.2.1.jar                   | None                                     |
	| UCHIJAAAA | display         | 1.2.4          | Display-1.2.4.jar                             | None                                     |
	| UCHIJAAAA | fastleafdecay   | v14            | FastLeafDecay-v14.jar                         | None                                     |
	| UCHIJAAAA | llibrary        | 1.7.18         | llibrary-1.7.18-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHIJAAAA | fossil          | 8.0.5          | fossilsarcheology-8.0.6.jar                   | None                                     |
	| UCHIJAAAA | furnaceoverhaul | 2.2.2          | furnaceoverhaul-1.12.2-2.2.2.jar              | None                                     |
	| UCHIJAAAA | cfm             | 6.3.0          | furniture-6.3.2-1.12.2.jar                    | None                                     |
	| UCHIJAAAA | harvest         | 1.12-1.2.7-20  | Harvest-1.12-1.2.7-20.jar                     | None                                     |
	| UCHIJAAAA | jei             | 4.15.0.275     | jei_1.12.2-4.15.0.275.jar                     | None                                     |
	| UCHIJAAAA | zawa            | 1.12.2-2.1.3   | zawa-1.12.2-2.1.3.jar                         | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
	| UCHIJAAAA | lilcritters     | 1.12.2-1.1.0.0 | lilcritters-1.12.2-1.1.0.0.jar                | None                                     |
	| UCHIJAAAA | modernlamps     | 1.0.3          | ModernLights-1.0.3_1.12.jar                   | None                                     |
	| UCHIJAAAA | waystones       | 4.1.0          | Waystones_1.12.2-4.1.0.jar                    | None                                     |
	| UCHIJAAAA | orelib          | 3.6.0.1        | OreLib-1.12.2-3.6.0.1.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 527.56' Renderer: 'NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2779
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 527.56, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: NotEnoughPixels1.12.2-1.1.0.1.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x AMD Ryzen 7 5700G with Radeon Graphics 
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 13
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.0 NVIDIA 527.56
	OpenGlRenderer: NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

I know its alot but i need help i cant laod into any of my worlds

thanks

**Comment by ViniciosSoder** [comment]
I just figured out how to make it work by finding the exactly point to turn off the Internet. I was relying in all DNS explanation (changing didn't work for me) and simple intuition for bypass, despite trying several times until I found the time, without depending for connection (in which the problem consists), specially using SKLaucher, which is after download some Forge extra files. We need to unplug the net cable before the executable's openning that shows their white mod loader screen; this is what will make requisitions for the fault GSON library used by the LLibrary.
