### ISSUE TITLE
1.7.4-1.11 Forge Hook Circularity

### ISSUE THREAD

**Issue by Rosethorns** [iLexiconn/LLibrary#40]
I have posted this over to the Literal Ascension issue tracker as well. But LL is on the stack too so here I am

It seems either LL or Literal Ascension is causing a ForgeHooks circularity problem and causes a crash on startup when paired with other mods that need ForgeHooks

`Caused by: java.lang.ClassCircularityError: net/minecraftforge/common/ForgeHooks
	at com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher.onInit(LiteralAscensionRuntimePatcher.kt:13) ~[LiteralAscensionRuntimePatcher.class:?]
	at net.ilexiconn.llibrary.server.asm.RuntimePatcher.transform(RuntimePatcher.java:38) ~[RuntimePatcher.class:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:253) ~[forge-1.11.2-13.20.0.2228.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 6 more`

**Comment by JamiesWhiteShirt** [comment]
This issue was resolved by using the right version of LLibrary with the right Minecraft version.
