### ISSUE TITLE
Crash report when loading game

### ISSUE THREAD

**Issue by comus777** [iLexiconn/LLibrary#43]
[crash-2017-02-27_17.03.10-client.txt](https://github.com/iLexiconn/LLibrary/files/803075/crash-2017-02-27_17.03.10-client.txt)
I get this when trying to load up LLibrary on the latest version for 1.7.10. Any clue why?

**Comment by gegy1000** [comment]
What happens if you only have LLibrary installed?

**Comment by Gegy** [comment]
LifeGuage requires LLibrary Legacy.

**Comment by comus777** [comment]
Now I get this crash when launching

Unable to launch
java.lang.RuntimeException: java.util.zip.ZipException: error in opening zip file
	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:137) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_121]
	at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[?:1.8.0_121]
	at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[?:1.8.0_121]
	at java.util.zip.ZipFile.<init>(ZipFile.java:163) ~[?:1.8.0_121]
	at net.ilexiconn.llibrary.common.plugin.LLibraryPlugin.call(LLibraryPlugin.java:69) ~[llibrary-0.7.0-1.7.10.jar:?]
	at net.ilexiconn.llibrary.common.plugin.LLibraryPlugin.call(LLibraryPlugin.java:25) ~[llibrary-0.7.0-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:133) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	... 2 more

**Comment by comus777** [comment]
Managed to solve that crash by unzipping and rezipping the .jar file but now I get this. 

[crash-2017-02-27_23.44.17-client.txt](https://github.com/iLexiconn/LLibrary/files/804162/crash-2017-02-27_23.44.17-client.txt)

This seems like an awfully troublesome API library.

**Comment by Gegy** [comment]
LLibrary Beta is no longer supported, so any problems it may have will not be fixed. Try run the game with *only* LifeGauge and LLibrary installed.
