### ISSUE TITLE
Crash, when server has not internet access.

### ISSUE THREAD

**Issue by jkroepke** [iLexiconn/LLibrary#46]
Stacktrace:
```
// Who set us up the TNT?

Time: 3/11/17 6:28 PM
Description: Failed to receive data from URL: http://pastebin.com/raw/EjsPPpVG

java.net.NoRouteToHostException: No route to host (Host unreachable)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1022)
        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1020)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1019)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
        at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1466)
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1464)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1463)
        at java.net.URL.openStream(URL.java:1045)
        at net.ilexiconn.llibrary.server.util.WebUtils.readURL(WebUtils.java:82)
        at net.ilexiconn.llibrary.server.update.UpdateHandler.lambda$registerUpdateChecker$2(UpdateHandler.java:58)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by Gegy** [comment]
Should be fixed in `0.7.5`
