### ISSUE TITLE
Server startup file not found exception

### ISSUE THREAD

**Issue by kmccmk9** [iLexiconn/LLibrary#67]
Hello using:

* `Forge: v14.23.3.2655`
* `Sponge Forge: 1.12.2-2655-7.1.0-BETA-3064`
* `LLibrary  1.7.9-1.12`

I am receiving the following stack trace error output in my console.

`[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: java.io.IOException: No such file or directory
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at java.io.UnixFileSystem.createFileExclusively(Native Method)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at java.io.File.createNewFile(File.java:1012)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at net.ilexiconn.llibrary.server.config.LLibraryConfig.load(LLibraryConfig.java:134)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at net.ilexiconn.llibrary.LLibrary.onPreInit(LLibrary.java:49)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
[14:17:49] [Server thread/INFO] [STDERR]: [net.ilexiconn.llibrary.server.config.LLibraryConfig:load:138]: 	at java.lang.Thread.run(Thread.java:748)`

**Comment by Gegy** [comment]
Thanks for the report, this should be fixed in release 1.7.10 (not MC version). :)
