### ISSUE TITLE
Server crash on startup with version llibrary-1.7.10-1.12.2

### ISSUE THREAD

**Issue by AdaraChristine** [iLexiconn/LLibrary#70]
forge-1.12.2-14.23.3.2691-universal
llibrary-1.7.10-1.12.2
1.12.2 MPserver

Time: 5/18/18 3:10 PM
Description: Exception in server tick loop

java.lang.NoSuchFieldError: prevRenderViewDistance
	at net.ilexiconn.llibrary.server.core.patcher.LLibraryHooks.<clinit>(LLibraryHooks.java:28)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:521)
	at java.lang.Thread.run(Unknown Source)

https://pastebin.com/5s50tN7j

**Comment by Gegy** [comment]
Fixed in 1.7.11. Thanks for the report!
