### ISSUE TITLE
LLibrary crashes with removed entries?

### ISSUE THREAD

**Issue by Darkhax** [iLexiconn/LLibrary#84]
```
java.lang.IllegalStateException: Entry was removed
	at java.util.IdentityHashMap$EntryIterator$Entry.checkIndexForEntryUse(IdentityHashMap.java:914)
	at java.util.IdentityHashMap$EntryIterator$Entry.getValue(IdentityHashMap.java:870)
	at net.ilexiconn.llibrary.server.ServerEventHandler.onServerTickEvent(ServerEventHandler.java:161)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_478_ServerEventHandler_onServerTickEvent_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```

| State     | ID                        | Version                      | Source                                                       | Signature                                |
|:--------- |:------------------------- |:---------------------------- |:------------------------------------------------------------ |:---------------------------------------- |
| UCHIJAAAA | minecraft                 | 1.12.2                       | minecraft.jar                                                | None                                     |
| UCHIJAAAA | mcp                       | 9.42                         | minecraft.jar                                                | None                                     |
| UCHIJAAAA | FML                       | 8.0.99.99                    | forge-14.23.4.2708.jar                                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHIJAAAA | forge                     | 14.23.4.2708                 | forge-14.23.4.2708.jar   
| UCHIJAAAA | llibrary                  | 1.7.13                       | llibrary-1.7.13-1.12.2.jar                                   | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |

**Comment by Gegy** [comment]
Fixed in LLibrary 1.7.14, thanks for the report. :)
