### ISSUE TITLE
Crash interaction with ExoticBirds and Mowziesmobs

### ISSUE THREAD

**Issue by LemADEC** [iLexiconn/LLibrary#86]
As of llibrary-1.7.14-1.12.2.jar, mowziesmobs-1.4.2.jar and Exotic Birds 1.12.2-1.4.1.jar, in single player, game is crashing when opening the ExoticBirds book:
```
Description: Rendering entity in world

java.lang.IllegalStateException: Cannot get entity data on entity without data cap
	at net.ilexiconn.llibrary.server.capability.EntityDataHandler.getEntityData(EntityDataHandler.java:52)
	at net.ilexiconn.llibrary.server.entity.EntityPropertiesHandler.getProperties(EntityPropertiesHandler.java:70)
	at com.bobmowzie.mowziesmobs.client.ClientEventHandler.onRenderLiving(ClientEventHandler.java:110)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1280_ClientEventHandler_onRenderLiving_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:78)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:41)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:16)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at pavocado.exoticbirds.gui.GuiBirdBookBeta.drawEntityOnScreen(GuiBirdBookBeta.java:425)
	at pavocado.exoticbirds.gui.GuiBirdBookBeta.func_146976_a(GuiBirdBookBeta.java:226)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at pavocado.exoticbirds.gui.GuiBirdBookBeta.func_73863_a(GuiBirdBookBeta.java:84)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.ilexiconn.llibrary.server.capability.EntityDataHandler.getEntityData(EntityDataHandler.java:52)
	at net.ilexiconn.llibrary.server.entity.EntityPropertiesHandler.getProperties(EntityPropertiesHandler.java:70)
	at com.bobmowzie.mowziesmobs.client.ClientEventHandler.onRenderLiving(ClientEventHandler.java:110)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1280_ClientEventHandler_onRenderLiving_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:78)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:41)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:16)

-- Entity being rendered --
Details:
	Entity Type: exoticbirds:cassowary (pavocado.exoticbirds.entity.Birds.EntityCassowary)
	Entity ID: 0
	Entity Name: Cassowary
	Entity's Exact location: 0.00, 0.00, 0.00
	Entity's Block location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: pavocado.exoticbirds.render.RenderCassowary@1ec69b07
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at pavocado.exoticbirds.gui.GuiBirdBookBeta.drawEntityOnScreen(GuiBirdBookBeta.java:425)
	at pavocado.exoticbirds.gui.GuiBirdBookBeta.func_146976_a(GuiBirdBookBeta.java:226)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at pavocado.exoticbirds.gui.GuiBirdBookBeta.func_73863_a(GuiBirdBookBeta.java:84)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)

-- Screen render details --
Details:
	Screen name: pavocado.exoticbirds.gui.GuiBirdBookBeta
	Mouse location: Scaled: (345, 209). Absolute: (691, 418)
	Screen size: Scaled: (692, 419). Absolute: (1383, 837). Scale factor of 2
```

**Comment by pau101** [comment]
Thank for the report! This issue has been known for a bit. Reported to Exotic Birds [here](https://minecraft.curseforge.com/projects/exotic-birds/issues/14). I have looked into it now and have identified it as an issue within Exotic Birds. I will be getting in touch with the developer to resolve it.

**Comment by pau101** [comment]
A quick workaround you can do is rename the Exotic Birds jar file to be after LLibrary alphabetically, e.g. append "z" to the beginning.

**Comment by LemADEC** [comment]
ExoticBirds was fixed.
Issue is not reproduced with LLibrary-1.7.15-1.12.2 + Exotic birds-1.12.2-2.1.0 + Mowzie's Mobs-1.4.2.
Hence closing.
