### ISSUE TITLE
Crash, can't find what mod 

### ISSUE THREAD

**Issue by mrtomwolf** [iLexiconn/LLibrary#88]
This crash happens when I start a server on linux.

llibrary 1.7.14 
forge 1.12.2-14.23.4.2745

debug.log
https://gist.github.com/mrtomwolf/1d8c7cf21c1a239570856df279c073b2

**Comment by Gegy** [comment]
Try the recommended Forge version
```
java.io.IOException: Unable to create parent directories of ./mods/memory_repo/net/ilexiconn/llibrary-core/1.0.6-1.12.2/llibrary-core-1.0.6-1.12.2.jar
	at com.google.common.io.Files.createParentDirs(Files.java:460) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.relauncher.libraries.LibraryManager.extractPacked(LibraryManager.java:343) [forge-1.12.2-14.23.4.2745-universal.jar:?]
	at net.minecraftforge.fml.relauncher.libraries.LibraryManager.extractPacked(LibraryManager.java:200) [forge-1.12.2-14.23.4.2745-universal.jar:?]
at net.minecraftforge.fml.relauncher.libraries.LibraryManager.cleanDirectory(LibraryManager.java:166) [forge-1.12.2-14.23.4.2745-universal.jar:?]
```

**Comment by mrtomwolf** [comment]
It works at 2718, needed by codechickenlib.

**Comment by Gegy** [comment]
Is this resolved?
